blogcine/config/routes.rb
Rails.application.routes.draw do
  resources :carters
  resources :carteleras

end

blogcine/app/models/cartelera.rb
class Cartelera < ActiveRecord::Base
end

blogcine/app/models/carter.rb
class Carter < ActiveRecord::Base
end

blogcine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogcine/app/controllers/carteleras_controller.rb
class CartelerasController < ApplicationController
  before_action :set_cartelera, only: [:show, :edit, :update, :destroy]

  # GET /carteleras
  # GET /carteleras.json
  def index
    @carteleras = Cartelera.all
  end

  # GET /carteleras/1
  # GET /carteleras/1.json
  def show
  end

  # GET /carteleras/new
  def new
    @cartelera = Cartelera.new
  end

  # GET /carteleras/1/edit
  def edit
  end

  # POST /carteleras
  # POST /carteleras.json
  def create
    @cartelera = Cartelera.new(cartelera_params)

    respond_to do |format|
      if @cartelera.save
        format.html { redirect_to @cartelera, notice: 'Cartelera was successfully created.' }
        format.json { render :show, status: :created, location: @cartelera }
      else
        format.html { render :new }
        format.json { render json: @cartelera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carteleras/1
  # PATCH/PUT /carteleras/1.json
  def update
    respond_to do |format|
      if @cartelera.update(cartelera_params)
        format.html { redirect_to @cartelera, notice: 'Cartelera was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartelera }
      else
        format.html { render :edit }
        format.json { render json: @cartelera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carteleras/1
  # DELETE /carteleras/1.json
  def destroy
    @cartelera.destroy
    respond_to do |format|
      format.html { redirect_to carteleras_url, notice: 'Cartelera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartelera
      @cartelera = Cartelera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartelera_params
      params.require(:cartelera).permit(:nombre, :rating)
    end
end

blogcine/app/controllers/carters_controller.rb
class CartersController < ApplicationController
  before_action :set_carter, only: [:show, :edit, :update, :destroy]

  # GET /carters
  # GET /carters.json
  def index
    @carters = Carter.all
  end

  # GET /carters/1
  # GET /carters/1.json
  def show
  end

  # GET /carters/new
  def new
    @carter = Carter.new
  end

  # GET /carters/1/edit
  def edit
  end

  # POST /carters
  # POST /carters.json
  def create
    @carter = Carter.new(carter_params)

    respond_to do |format|
      if @carter.save
        format.html { redirect_to @carter, notice: 'Carter was successfully created.' }
        format.json { render :show, status: :created, location: @carter }
      else
        format.html { render :new }
        format.json { render json: @carter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carters/1
  # PATCH/PUT /carters/1.json
  def update
    respond_to do |format|
      if @carter.update(carter_params)
        format.html { redirect_to @carter, notice: 'Carter was successfully updated.' }
        format.json { render :show, status: :ok, location: @carter }
      else
        format.html { render :edit }
        format.json { render json: @carter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carters/1
  # DELETE /carters/1.json
  def destroy
    @carter.destroy
    respond_to do |format|
      format.html { redirect_to carters_url, notice: 'Carter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carter
      @carter = Carter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carter_params
      params.require(:carter).permit(:cartelera, :nombre, :rating)
    end
end

blogcine/app/helpers/application_helper.rb
module ApplicationHelper
end

blogcine/app/helpers/carteleras_helper.rb
module CartelerasHelper
end

blogcine/app/helpers/carters_helper.rb
module CartersHelper
end

blogcine/app/views/carteleras/_form.html.erb
<%= form_for(@cartelera) do |f| %>
  <% if @cartelera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cartelera.errors.count, "error") %> prohibited this cartelera from being saved:</h2>

      <ul>
      <% @cartelera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogcine/app/views/carteleras/edit.html.erb
<h1>Editing Cartelera</h1>

<%= render 'form' %>

<%= link_to 'Show', @cartelera %> |
<%= link_to 'Back', carteleras_path %>

blogcine/app/views/carteleras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carteleras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carteleras.each do |cartelera| %>
      <tr>
        <td><%= cartelera.nombre %></td>
        <td><%= cartelera.rating %></td>
        <td><%= link_to 'Show', cartelera %></td>
        <td><%= link_to 'Edit', edit_cartelera_path(cartelera) %></td>
        <td><%= link_to 'Destroy', cartelera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartelera', new_cartelera_path %>

blogcine/app/views/carteleras/new.html.erb
<h1>New Cartelera</h1>

<%= render 'form' %>

<%= link_to 'Back', carteleras_path %>

blogcine/app/views/carteleras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cartelera.nombre %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @cartelera.rating %>
</p>

<%= link_to 'Edit', edit_cartelera_path(@cartelera) %> |
<%= link_to 'Back', carteleras_path %>

blogcine/app/views/carters/_form.html.erb
<%= form_for(@carter) do |f| %>
  <% if @carter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carter.errors.count, "error") %> prohibited this carter from being saved:</h2>

      <ul>
      <% @carter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cartelera %><br>
    <%= f.text_field :cartelera %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogcine/app/views/carters/edit.html.erb
<h1>Editing Carter</h1>

<%= render 'form' %>

<%= link_to 'Show', @carter %> |
<%= link_to 'Back', carters_path %>

blogcine/app/views/carters/index.html.erb
<p id="notice"><%= notice %></p> 
<h1>Estrenos 2015 Carters</h1>

<table>
  <thead>
    <tr>
 
&iexcl;Bienvenidos, esta es mi&nbsp;&nbsp;&nbsp;1&ordf;&nbsp;&nbsp;&nbsp;p&aacute;gina!


    <pre>CARLOS HERNANDEZ LINUX UNITEC SPS</pre>

 <textarea name="ejemploarea" cols="30" rows="3">Escribe el texto que quieras</textarea> 

    <embed src="varios/audio.mid" autostart="false" loop="true">

 <a href="mailto:carlosmauriciohernandezdiaz@gmail.com">carlosmauriciohernandezdiaz@gmail.com</a>
      <th>Cartelera</th>
      <th>Nombre</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<body leftmargin="20" topmargin="0" marginwidth="20" marginheight="0" >
<marquee bgcolor="#006699" behavior="alternate" direction="right">
  <b><font color="#FFFFCC" size="5">CARTELERA DE PELICULAS SPS HONDURAS 2015 </font></b>

  <tbody>
    <% @carters.each do |carter| %>
      <tr>
        <td><%= carter.cartelera %></td>
        <td><%= carter.nombre %></td>
        <td><%= carter.rating %></td>
        <td><%= link_to 'Show', carter %></td>
        <td><%= link_to 'Edit', edit_carter_path(carter) %></td>
        <td><%= link_to 'Destroy', carter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carter', new_carter_path %>

blogcine/app/views/carters/new.html.erb
<h1>New Carter</h1>

<%= render 'form' %>

<%= link_to 'Back', carters_path %>

blogcine/app/views/carters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cartelera:</strong>
  <%= @carter.cartelera %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @carter.nombre %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @carter.rating %>
</p>

<%= link_to 'Edit', edit_carter_path(@carter) %> |
<%= link_to 'Back', carters_path %>

blogcine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogcine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>